project:
  type: book

book:
  title: "Improving your statistical inferences through Monte Carlo simulations"
  subtitle: "in R and tidyverse"
  author:
    - name: Ian Hussey
      orcid: 0000-0001-8906-7559
      email: ian.hussey@unibe.ch
    - name: Jamie Cummins
      orcid: 0000-0002-9729-4900
      email: jamie.cummins@unibe.ch
  date: today
  chapters:
    - index.qmd

    - part: "Part I: Learning to Simulate"
      chapters: 
        - chapters/1_required_skills.qmd 
        - chapters/2_foundation_concepts.qmd 
        - chapters/3_writing_functions.qmd 
        - chapters/4_data_generating_process_functions.qmd 
        - chapters/5_pseudo_random_number_generators.qmd
        - chapters/6_analysis_functions.qmd 
        - chapters/7_creating_simulation_experiments.qmd 
        - chapters/8_mapping.qmd 
        - chapters/9_summarizing_results.qmd 
        - chapters/10_planning_and_reporting.qmd 
        - chapters/11_simulation_template.qmd 
        
    - part: "Part II: Learning from Simulations"
      chapters:
        - chapters/violating_assumptions.qmd
        - chapters/testing_assumptions_and_conditional_tests.qmd
        - chapters/p_hacking.qmd
        - chapters/p_values_and_confidence_intervals.qmd
        - chapters/difference_between_significant_and_nonsignificant.qmd
        - chapters/standardized_effect_sizes_and_range_restriction.qmd
        - chapters/impact_of_careless_responding.qmd
        - chapters/meta_analysis_and_publication_bias.qmd
        - chapters/causality.qmd

    - part: "Exercises"
      chapters:
        - exercises/1_required_skills_exercises.qmd
        - exercises/3_writing_functions_exercises.qmd
        - exercises/4_data_generating_process_functions_exercises.qmd
        
    - part: "Appendices"
      chapters:
        - appendices/lesson_plan.qmd
        - appendices/ADEMP_preregistration_template.qmd
        - appendices/crowded_room_problem.qmd
        - license.qmd

# bibliography: references.bib

format:
  html:
    toc: true
    toc_float: true
    code-fold: show
    code-tools: true
    warning: false
    theme: cosmo
    #embed-resources: false
    #highlight: haddock

editor: visual

cover-image: cover.png

