# Lesson plan <span class="badge badge-draft1">✎ Very rough draft</span>

- badge 1 <span class="badge badge-draft1">✎ Very rough draft</span>
- badge 2 <span class="badge badge-draft2">✎ Rough draft</span>
- badge 3 <span class="badge badge-draft3">✎ Polishing</span>
- badge 4 <span class="badge badge-complete">✓ Complete</span>

If delivered as a semester-long course, we suggest the following lesson plan. 

Notes to self on structure

- part: "Part I: Learning to Simulate"
      chapters: 
        - chapters/1_required_skills.qmd # week 1 homework
        - chapters/2_foundation_concepts.qmd # week 1 ian
        - chapters/3_writing_functions.qmd # week 1 jamie
        - chapters/4_data_generating_process_functions.qmd # week 2 - really about practicing writing functions, summarizing and plotting - ian
        - chapters/5_analysis_functions.qmd # week 3 - practice writing functions again, more/less flexible/reusable - jamie
        - chapters/6_creating_simulation_experiments.qmd # week 4, if it includes Siepe's study on designs
        - chapters/7_mapping.qmd # week 4 - nested dfs needs explaining. 
        - chapters/8_summarizing_results.qmd # week 5
        - chapters/9_planning_and_reporting.qmd # come back to this after substantive chapter 1 - week 7?, Siepe paper, assessing performance (MC SE), etc. Diagnostics on already run simulations, go in and check specific iterations, run manually etc.
        # maybe add sth here on parallelisation and optimisation, eg dropping the nested datasets and using a helper function to use pmap() more directly and efficiently?
        - chapters/10_simulation_template.qmd # week 5, 'putting it all together'; skip to substantive chapter 1?

    - part: "Part II: Learning from Simulations"
      chapters:
        # whatever chapter comes next, lay out the final assignment here
        # substantive chapter 1 - week 5/6
        - chapters/violating_assumptions.qmd

## Week 1

In class

- Slides in [keynote](../slides/week1/simulation_week_1.key), [powerpoint](../slides/week1/simulation_week_1.pptx), or [pdf](../slides/week1/simulation_week_1.pdf).

After class

- [Chapter 1: Required skills](../chapters/1_required_skills.qmd) and its exercises.
- [Chapter 2: Foundation concepts](../chapters/2_foundation_concepts.qmd).

## Week 2

In class

- [Chapter 3: Writing functions](../chapters/3_writing_functions.qmd).

After class

- Chapter 3's exercises (linked in chapter).

## Week 3

In class

- [Slides: Is this normally distributed?](../slides/week3/is_this_normally_distributed.html).
- [Chapter 4: Data Generating Process functions](../chapters/4_data_generating_process_functions.qmd).

After class

- Chapter 4's exercises (linked in chapter).
- [Chapter 5: Pseudo-random number generators](../chapters/5_pseudo_random_number_generators.qmd).

## Week 4

In class

- [Chapter 5: Analysis functions](../chapters/5_analysis_functions.qmd).
- [Chapter 11: Everything is regression](../chapters/11_everything_is_regression.qmd).

After class

- Chapter 5's exercises (linked in chapter).

## Week 5

In class

- [Chapter 6: Creating simulation experiments](../chapters/6_creating_simulation_experiments.qmd). 
- [Chapter 7: Mapping functions](../chapters/7_mapping.qmd). 

After class

- XX

## Week 6

In class

- [Chapter 8: Summarizing results](../chapters/8_summarizing_results.qmd).
- [Chapter 10: Summarizing results](../chapters/10_simulation_template.qmd).

After class

- XX

## Week 7

In class

- XX

After class

- XX

## Week 8

In class

- XX

After class

- XX

## Week 9

In class

- XX

After class

- XX

## Week 10

In class

- XX

After class

- XX

## Week 11

In class

- XX

After class

- XX

## Week 12

In class

- XX

After class

- XX

## Week 13

In class

- XX

After class

- XX

## Week 14

In class

- XX

After class

- XX

